---
title: "Decreasing Prevalence of COVID-19 Cases in Toronto"
author: "Denise Chang"
thanks: "Code and data supporting this analysis are available at: https://github.com/DeniseChang9/Covid-19_Cases.git "
date: today
date-format: long
abstract: "The coronavirus disease, better known as COVID-19, is an infectious disease that first emerged in 2019, soon resulting in a global pandemic half a year later. This study aims to investigate the trends in COVID-19 cases in the City of Toronto from 2020 to 2023, as well as the severity of each of these cases. Based on the exploration of the number of reported cases, the number of cases who were hospitalized and the number of cases who were sent to the ICU, there is strong evidence support the hypothesis that the coronavirus disease is no longer a major threat to society as is was during the peak of the pandemic. The results of this study is significant, as it impacts the future directions of COVID-19 regulations for businesses, schools and governmental institutions."
format: pdf
number-sections: true
bibliography: references.bib
---

# Introduction
The coronavirus disease, also commonly referred to as COVID-19, is a contagious disease which first emerged in late 2019 [@PHO]. Due to the scale of the coronavirus outbreak and its rapid international transmission rate, the World's Health Organization (WHO) characterized it to be a global pandemic and a public health emergency of international on concern (PHEIC) on March 11th 2020 [@WHO]. This statement urged national leaders to begin formulating a response plan, including but not limited to masking restrictions and mandatory vaccination policies to limit the spread of the virus. However, in early 2022, despite the ongoing PHEIC, the province of Ontario announced they would lift all COVID-19 related by the end of April 2022 [@CTV]. This announcement was welcomed with skepticism as the public was still not convinced about the safety of lifting these regulations [@CBC].

One of the ways to evaluate the safety of lifting COVID-19 regulations as well as its effectiveness would be to look at the number of cases of COVID-19 and the severity of each case for the years surrounding the loosening of regulations. In this paper I take a particular interest in the data surrounding the reported cases of COVID-19 in the city of Toronto from 2020 to 2023. I estimate the transmission rate of the disease during the pandemic by evaluating the number of cases reported by month. The severity of each case is evaluated by compiling the number of patients who were hospitalized and sent to the intensive care unit (ICU) during their confirmed episode of sickness. (I find that the number of reported COVID-19 cases were already decreasing by the time Ontario announced they would lift all COVID-19 related regulations, and that the cases kept decreasing after they were lifted. The severity of the cases, however rose after the regulations were lifted.)?

The remainder of this paper is structured in four subsequent sections. Section 2 discusses the data source used for analysis and the cleaning of the data. Section 3 will discuss the results of the study including the trends found by exploring the cleaned data set. Section 4 provides further insights on the findings of the study and will discuss the weaknesses of limitations of this analysis. Finally section 5 concludes the analysis by presenting a summary of the main findings discussed throughout this paper. 

```{r}
#| message: false
#| echo: false

#### Workspace set-up ####
library(tidyverse)
library(knitr)
library(here)
library(arrow)

#### Read cleaned dataset ####
clean_covid_data <-
  read_parquet(
    file = here("outputs/data/clean_covid_data.parquet"),
  )
```


# Data
In this section I will present the acquisition method of the data, the variables of interest for this analysis as well as the method of data processing. 

## Data Collection
The data used in this paper is retrieved from the City of Toronto Open Data Portal through the R package `opendatatoronto` [@opendatatoronto]. The downloaded data set is titled "COVID-19 Cases in Toronto". Starting from the first reported case in January 2020, the data uses 13 variables to capture demographic, geographic and severity information about the cases reported to and managed by Toronto Public Health. The data is extracted on a bi-weekly basis from the provincial Case & Contact Management System (CCM) to keep the reports accurate and relevant to the present.

The data used for this paper was retrieved on January 20 2024, and was last refreshed on January 17 2024. 

## Variables of Interest
For this analysis the variables of interests are the number of reported COVID-19 cases in Toronto, the number of patients who had been hospitalized for a reason related to their sickness, and the number of patients who had been to the ICU for their sickness. These three variables are used to evaluate the transmission rate and the severity of the disease of each month in the studied years. 

To evaluate the transmission rate of the virus, the variable of interest I compiled the number of reported cases of COVID-19 per month from January 2020 to December 2023. This variable captures both confirmed cases and probably cases due to reasonable suspicion. 

To estimate the severity of the cases, I am interested in the number of confirmed patients who has been hospitalized for reasons related to the coronavirus disease and the number of patients who were admitted to the ICU for the same reasons. Both of these variables includes those who are currently hospitalized, those who have been discharged and those who are deceased. 

Another possible variable from the same dataset that could have been used to estimate the severity of the reported cases is the number of patients who has been intubated during their episode. This variable was not considered for this analysis as intubation is a mandatory step for patients sent to the ICU. As this variable is already captures by another variable of interest, it was omitted for the purpose of this paper.  



## Data Processing

# Results

# Discussion

# Conclusion

# References
